### ISSUE TITLE
yd_array_flatten 可以使用 原生函数

### ISSUE THREAD

**Issue by Coaixy** [chenbimo/yidash#35]
![421722390555_ pic](https://github.com/user-attachments/assets/49ca1587-eeb3-41c4-9e37-756167aefcaa)
![401722390534_ pic](https://github.com/user-attachments/assets/633ded5b-d76c-47b5-95a5-52e487e69fd6)
![431722390603_ pic](https://github.com/user-attachments/assets/f4013672-1064-447e-af12-9a0a127cfb23)

**Comment by chenbimo** [comment]
收到，感谢反馈，这个工具函数要调整调整。
